/**
 * 功能：动作定义
 * 作者：安超
 * 日期：2017/6/29
 */
export const SHOWLOADING_COMMON = 'SHOWLOADING_COMMON';
export const HIDELOADING_COMMON = 'HIDELOADING_COMMON';
export const INCREASEINVOKE_COMMON = 'INCREASEINVOKE_COMMON';
export const DECREASEINVOKE_COMMON = 'DECREASEINVOKE_COMMON';
